[deploy]
bucket = 'cfn-artifacts'
region = 'ca-central-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:ca-central-1:632626636018:certificate/dfc95f52-1d5e-4a32-97ba-a04cc6eaf397'
NetworkingStack = 'CrdNet'