AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  WwwBucketName:
    Type: String
  distributionId:
    Type: String

Resources:
  GitHubOIDCProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      ClientIdList:
        - "sts.amazonaws.com"
      ThumbprintList:
        - "6938fd4d98bab03faadb97b34396831e3780aea1"
      Url: https://token.actions.githubusercontent.com

  GitHubActionsRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "GitHubActionsRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                {
                  "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
                  "token.actions.githubusercontent.com:sub": "repo:poxrud/aws-bootcamp-cruddur-2023:ref:refs/heads/prod-frontend",
                }
  SyncToS3BucketPermission:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: SyncToS3BucketPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::${WwwBucketName}"
              - !Sub "arn:aws:s3:::${WwwBucketName}/*"
          - Effect: Allow
            Action:
              - "cloudfront:CreateInvalidation"
            Resource:
              - !Sub "arn:aws:cloudfront::632626636018:distribution/${distributionId}"
      Roles:
        - !Ref GitHubActionsRole
