# Build and Deploy the frontend assets to AWS S3

name: Deploy frontend

on:
  pull_request:
    branches: [prod-frontend]

env:
  AWS_REGION: "ca-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          debug: true
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)

  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "18.x"

      # - name: Install npm packages
      #   run: |
      #     cd frontend-react-js
      #     npm i

      # - name: Build prod
      #   continue-on-error: true
      #   run: ./bin/frontend/static-build

      # - name: Show created folder
      #   run: ls -al frontend-react-js/build/

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_TOKEN: ${{ toJson(github) }}
      #   run: echo "$GITHUB_TOKEN"

      # - name: Dump web id token2
      #   with:
      #     debug: true
      #   run: echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::632626636018:role/GitHubActionsRole
          role-session-name: GitHub_OIDC
          aws-region: ${{env.AWS_REGION}}

      - name: try to run aws command.
        run: aws sts get-caller-identity
