# Build and Deploy the frontend assets to AWS S3

name: Deploy frontend

on:
  pull_request:
    branches: [prod-frontend]

env:
  AWS_REGION: "ca-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "18.x"

      # - name: Install npm packages
      #   run: |
      #     cd frontend-react-js
      #     npm i

      # - name: Build prod
      #   continue-on-error: true
      #   run: ./bin/frontend/static-build

      # - name: Show created folder
      #   run: ls -al frontend-react-js/build/

      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ toJson(github.token) }}
        run: echo "$GITHUB_TOKEN" | sed 's/./& /g'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::632626636018:role/GitHubActionsRole
          role-session-name: GitHub_OIDC
          aws-region: ${{env.AWS_REGION}}

      - name: try to run aws command.
        run: aws sts get-caller-identity
